## Problem Statement: classify the Size_Categorie using SVM

In [1]:
# SVM Classification
import pandas as pd
from pandas import read_csv
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [2]:
forest = pd.read_csv('forestfires.csv')
forest

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0          small  
1           0          small  
2           0          small  
3           0          small  
4           0          small  
..        ...            ...  
512         0          large  
513         0          large  
514         0          large  
515         0          small  
516         0          small  

[517 rows x 31 columns]

In [3]:
forest.nunique()

month             12
day                7
FFMC             106
DMC              215
DC               219
ISI              119
temp             192
RH                75
wind              21
rain               7
area             251
dayfri             2
daymon             2
daysat             2
daysun             2
daythu             2
daytue             2
daywed             2
monthapr           2
monthaug           2
monthdec           2
monthfeb           2
monthjan           2
monthjul           2
monthjun           2
monthmar           2
monthmay           2
monthnov           2
monthoct           2
monthsep           2
size_category      2
dtype: int64

In [4]:
forest[forest.duplicated()]

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
53    aug  wed  92.1  111.2  654.1   9.6  20.4  42   4.9   0.0  ...         0   
100   aug  sun  91.4  142.4  601.4  10.6  19.8  39   5.4   0.0  ...         0   
215   mar  sat  91.7   35.8   80.8   7.8  17.0  27   4.9   0.0  ...         0   
303   jun  fri  91.1   94.1  232.1   7.1  19.2  38   4.5   0.0  ...         0   
426   aug  thu  91.6  248.4  753.8   6.3  20.4  56   2.2   0.0  ...         0   
461   aug  sat  93.7  231.1  715.1   8.4  18.9  64   4.9   0.0  ...         0   
501   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8  ...         0   
508   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
53          0         0         0         0         0         0         0   
100         0         0         0         0         0         0         0   
215         0         0         0         1         0         0         0   
303         0         0         1         0         0         0         0   
426         0         0         0         0         0         0         0   
461         0         0         0         0         0         0         0   
501         0         0         0         0         0         0         0   
508         0         0         0         0         0         0         0   

     monthsep  size_category  
53          0          small  
100         0          small  
215         0          large  
303         0          small  
426         0          small  
461         0          small  
501         0          small  
508         0          small  

[8 rows x 31 columns]

In [5]:
forest.drop_duplicates(inplace=True)

In [6]:
forest.columns

Index(['month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind',
       'rain', 'area', 'dayfri', 'daymon', 'daysat', 'daysun', 'daythu',
       'daytue', 'daywed', 'monthapr', 'monthaug', 'monthdec', 'monthfeb',
       'monthjan', 'monthjul', 'monthjun', 'monthmar', 'monthmay', 'monthnov',
       'monthoct', 'monthsep', 'size_category'],
      dtype='object')

In [7]:
forest.drop(['dayfri', 'daymon', 'daysat', 'daysun', 'daythu',
       'daytue', 'daywed', 'monthapr', 'monthaug', 'monthdec', 'monthfeb',
       'monthjan', 'monthjul', 'monthjun', 'monthmar', 'monthmay', 'monthnov',
       'monthoct', 'monthsep'],axis=1,inplace=True)

In [8]:
forest

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00   

    size_category  
0           small  
1           small  
2           small  
3           small  
4           small  
..            ...  
512         large  
513         large  
514         large  
515         small  
516         small  

[509 rows x 12 columns]

In [9]:
forest.describe()

FFMC         DMC          DC         ISI        temp          RH  \
count  509.000000  509.000000  509.000000  509.000000  509.000000  509.000000   
mean    90.618075  110.235756  547.787623    9.023576   18.865422   44.253438   
std      5.555527   63.804112  248.196222    4.585083    5.841083   16.365192   
min     18.700000    1.100000    7.900000    0.000000    2.200000   15.000000   
25%     90.200000   62.300000  437.700000    6.400000   15.400000   32.000000   
50%     91.600000  108.300000  664.200000    8.400000   19.300000   42.000000   
75%     92.900000  141.300000  713.900000   11.000000   22.800000   53.000000   
max     96.200000  291.300000  860.600000   56.100000   33.300000  100.000000   

             wind        rain         area  
count  509.000000  509.000000   509.000000  
mean     4.011395    0.020432    12.992908  
std      1.800926    0.296261    64.133357  
min      0.400000    0.000000     0.000000  
25%      2.700000    0.000000     0.000000  
50%      4.000000    0.000000     0.610000  
75%      4.900000    0.000000     6.580000  
max      9.400000    6.400000  1090.840000

In [10]:
le = LabelEncoder()
forest['size_category'] = le.fit_transform(forest['size_category'])

In [11]:
forest.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0   

   size_category  
0              1  
1              1  
2              1  
3              1  
4              1

In [12]:
forest.day.unique()

array(['fri', 'tue', 'sat', 'sun', 'mon', 'wed', 'thu'], dtype=object)

In [13]:
forest.month.unique()

array(['mar', 'oct', 'aug', 'sep', 'apr', 'jun', 'jul', 'feb', 'jan',
       'dec', 'may', 'nov'], dtype=object)

In [14]:
forest['month'] = forest['month'].replace({'jan':1, 'feb':2, 'mar':3, 'apr':4, 'may':5, 'jun':6,
                     'jul':7, 'aug':8, 'sep':9, 'oct':10, 'nov':11, 'dec': 12})

In [15]:
forest['day'] = forest['day'].replace({'mon':1, 'tue':2, 'wed':3, 'thu':4, 'fri':5, 'sat':6,
                     'sun':7})

In [16]:
forest

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  \
0        3    5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00   
1       10    2  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00   
2       10    6  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00   
3        3    5  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00   
4        3    7  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00   
..     ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...   
512      8    7  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44   
513      8    7  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29   
514      8    7  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16   
515      8    6  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00   
516     11    2  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00   

     size_category  
0                1  
1                1  
2                1  
3                1  
4                1  
..             ...  
512              0  
513              0  
514              0  
515              1  
516              1  

[509 rows x 12 columns]

In [17]:
array = forest.values
array

array([[ 3.  ,  5.  , 86.2 , ...,  0.  ,  0.  ,  1.  ],
       [10.  ,  2.  , 90.6 , ...,  0.  ,  0.  ,  1.  ],
       [10.  ,  6.  , 90.6 , ...,  0.  ,  0.  ,  1.  ],
       ...,
       [ 8.  ,  7.  , 81.6 , ...,  0.  , 11.16,  0.  ],
       [ 8.  ,  6.  , 94.4 , ...,  0.  ,  0.  ,  1.  ],
       [11.  ,  2.  , 79.5 , ...,  0.  ,  0.  ,  1.  ]])

In [18]:
X = array[:,:-1]
Y = array[:,-1]

In [19]:
X

array([[ 3.  ,  5.  , 86.2 , ...,  6.7 ,  0.  ,  0.  ],
       [10.  ,  2.  , 90.6 , ...,  0.9 ,  0.  ,  0.  ],
       [10.  ,  6.  , 90.6 , ...,  1.3 ,  0.  ,  0.  ],
       ...,
       [ 8.  ,  7.  , 81.6 , ...,  6.7 ,  0.  , 11.16],
       [ 8.  ,  6.  , 94.4 , ...,  4.  ,  0.  ,  0.  ],
       [11.  ,  2.  , 79.5 , ...,  4.5 ,  0.  ,  0.  ]])

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
rescaled = scaler.fit_transform(X)

In [21]:
X=rescaled
X

array([[-1.96435265,  0.36038654, -0.79603981, ...,  1.49437016,
        -0.06903477, -0.20279135],
       [ 1.10403336, -1.08399732, -0.00325666, ..., -1.72936355,
        -0.06903477, -0.20279135],
       [ 1.10403336,  0.84184783, -0.00325666, ..., -1.50703709,
        -0.06903477, -0.20279135],
       ...,
       [ 0.22735164,  1.32330912, -1.62485856, ...,  1.49437016,
        -0.06903477, -0.02860775],
       [ 0.22735164,  0.84184783,  0.68141971, ..., -0.00633347,
        -0.06903477, -0.20279135],
       [ 1.54237422, -1.08399732, -2.00323234, ...,  0.27157461,
        -0.06903477, -0.20279135]])

In [22]:
Y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [23]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3, random_state=3)

## Linear

In [24]:
from sklearn.svm import SVC
model_linear = svm.SVC(kernel = "linear",C=100)
model_linear.fit(x_train,y_train)
pred_test_linear = model_linear.predict(x_test)
model_linear.score(x_test, y_test)

0.9738562091503268

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, pred_test_linear)
cm

array([[ 46,   1],
       [  3, 103]], dtype=int64)

In [26]:
#Grid Search CV
clf = SVC()
param_grid = [{'kernel':['linear'],'gamma':[100,50,0.5,0.1,0.01],'C':[15,14,13,12,0.001,0.0001]}]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 0.001, 0.0001],
                          'gamma': [100, 50, 0.5, 0.1, 0.01],
                          'kernel': ['linear']}])

In [27]:
gsv.best_params_ , gsv.best_score_ 

({'C': 14, 'gamma': 100, 'kernel': 'linear'}, 0.9776190476190477)

## Poly

In [28]:
model_poly = svm.SVC(kernel = "poly", C=50)
model_poly.fit(x_train, y_train)
pred_test_poly = model_poly.predict(x_test)
np.mean(pred_test_poly==y_test)

0.7843137254901961

In [29]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, pred_test_poly)
cm

array([[22, 25],
       [ 8, 98]], dtype=int64)

In [30]:
#Grid Search CV
clf = SVC()
param_grid = [{'kernel':['poly'],'gamma':[200,150,100,50,0.5,0.1,0.01],'C':[30,25,20,15,14,13,12,0.001,0.0001]}]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [30, 25, 20, 15, 14, 13, 12, 0.001, 0.0001],
                          'gamma': [200, 150, 100, 50, 0.5, 0.1, 0.01],
                          'kernel': ['poly']}])

In [31]:
gsv.best_params_ , gsv.best_score_ 

({'C': 30, 'gamma': 0.1, 'kernel': 'poly'}, 0.8568253968253968)

## RBF

In [32]:
model_rbf = svm.SVC(kernel = "rbf", C=25, gamma=0.01)
model_rbf.fit(x_train,y_train)
pred_test_rbf = model_rbf.predict(x_test)

np.mean(pred_test_rbf==y_test)

0.8169934640522876

In [33]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, pred_test_rbf)
cm

array([[ 20,  27],
       [  1, 105]], dtype=int64)

In [34]:
#Grid Search CV
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[200,150,100,50,0.5,0.1,0.01],'C':[20,15,14,13,12,0.001,0.0001]}]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [20, 15, 14, 13, 12, 0.001, 0.0001],
                          'gamma': [200, 150, 100, 50, 0.5, 0.1, 0.01],
                          'kernel': ['rbf']}])

In [35]:
gsv.best_params_ , gsv.best_score_ 

({'C': 14, 'gamma': 0.1, 'kernel': 'rbf'}, 0.8734920634920634)